# Generated by Django 6.0.4 on 2026-04-20 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useractivetoken',
            old_name='user_id',
            new_name='user',
        ),
    ]
