# Generated by Django 6.0.4 on 2026-04-22 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_remove_users_role_adminuser_adminuseractivetoken_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teams',
            old_name='department_id',
            new_name='department',
        ),
    ]
