# Generated by Django 6.0.4 on 2026-04-22 07:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_rename_department_id_teams_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamusermapping',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='service.teams'),
        ),
        migrations.AlterField(
            model_name='teamusermapping',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='service.users'),
        ),
        migrations.AlterUniqueTogether(
            name='teamusermapping',
            unique_together={('team', 'user')},
        ),
    ]
