# Generated by Django 6.0.4 on 2026-04-22 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_alter_teamusermapping_team_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teams',
            old_name='isactive',
            new_name='is_active',
        ),
        migrations.RemoveField(
            model_name='teams',
            name='department',
        ),
    ]
