# Generated by Django 6.0.4 on 2026-04-30 04:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0006_rename_isactive_teams_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='service.departmentmaster'),
        ),
    ]
