# Generated by Django 6.0.4 on 2026-04-30 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0007_users_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departmentmaster',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='service.users'),
        ),
        migrations.AlterField(
            model_name='teams',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='service.users'),
        ),
        migrations.RemoveField(
            model_name='adminuseractivetoken',
            name='admin',
        ),
        migrations.RemoveField(
            model_name='roles',
            name='permission',
        ),
        migrations.AddField(
            model_name='users',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='user_type',
            field=models.CharField(choices=[('USER', 'User'), ('ADMIN', 'Admin'), ('SUPER_ADMIN', 'Super Admin')], default='USER', max_length=20),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='DailyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateField()),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.users')),
            ],
            options={
                'db_table': 'daily_report',
            },
        ),
        migrations.CreateModel(
            name='DailyTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_development_task', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='not_started', max_length=20)),
                ('hours', models.IntegerField(default=0)),
                ('minutes', models.IntegerField(default=0)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='service.dailyreport')),
            ],
            options={
                'db_table': 'daily_task',
            },
        ),
        migrations.CreateModel(
            name='TaskPRLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pr_url', models.URLField()),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pr_links', to='service.dailytask')),
            ],
            options={
                'db_table': 'task_pr_link',
            },
        ),
        migrations.DeleteModel(
            name='AdminUser',
        ),
        migrations.DeleteModel(
            name='AdminUserActiveToken',
        ),
        migrations.DeleteModel(
            name='Permissions',
        ),
        migrations.DeleteModel(
            name='Roles',
        ),
        migrations.AddIndex(
            model_name='dailyreport',
            index=models.Index(fields=['user', 'report_date'], name='daily_repor_user_id_9b024e_idx'),
        ),
        migrations.AddIndex(
            model_name='dailyreport',
            index=models.Index(fields=['status'], name='daily_repor_status_c707fc_idx'),
        ),
        migrations.AddConstraint(
            model_name='dailyreport',
            constraint=models.UniqueConstraint(fields=('user', 'report_date'), name='unique_user_report_per_day'),
        ),
        migrations.AddIndex(
            model_name='dailytask',
            index=models.Index(fields=['report'], name='daily_task_report__47773b_idx'),
        ),
        migrations.AddIndex(
            model_name='dailytask',
            index=models.Index(fields=['status'], name='daily_task_status_872574_idx'),
        ),
        migrations.AddIndex(
            model_name='taskprlink',
            index=models.Index(fields=['task'], name='task_pr_lin_task_id_66e991_idx'),
        ),
    ]
